default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password

development:
  <<: *default
  database: dankainstagram

test:
  <<: *default
  database: dankainstagram_test

production:
  <<: *default
  database: dankainstagram
